// The meeting-canvas contract.
//
// This file IS the product surface. Recall.ai streams a webpage as the bot's screen share, so the
// canvas is a URL and everything on it arrives as one JSON document — no imperative drawing API, no
// per-widget endpoints. A producer (later: the transcript pipeline) POSTs a `CanvasDoc`; the page
// renders it. That constraint is deliberate: a pure data contract can be generated by a model,
// replayed from a log, diffed between revisions, and unit-tested without a browser.
//
// Design rules that shaped the schema:
//  · Every block is a tagged union member, so an unknown `kind` can be skipped rather than crashing
//    a live client meeting. Forward compatibility matters more than strictness here.
//  · Layout is data (`span`), not CSS the producer has to know. The model decides emphasis; the
//    renderer owns aesthetics. A producer can never make the canvas ugly.
//  · No block carries colour or font. Theming stays in one place so the canvas can't drift from the
//    dashboard it lives in.

/** How many of the 6 grid columns a block occupies. Omitted = a sensible per-kind default. */
export type Span = 2 | 3 | 4 | 6;

export type Person = {
  name: string;
  /** Shown under the name — "QDN · CEO", "Investor". Keep it short; this is read at a distance. */
  role?: string;
  /** Drives the initials chip tint. Any string; hashed to a hue so the same person is stable. */
  key?: string;
  /** Currently speaking — renders a live ring. */
  speaking?: boolean;
};

export type Todo = {
  text: string;
  /** Display name, not an email — the canvas is on a screen share with clients in the room. */
  owner?: string;
  due?: string;
  done?: boolean;
};

export type Decision = {
  text: string;
  /** Freeform: "agreed", "parked", "rejected". Drives the status dot only. */
  status?: "agreed" | "parked" | "rejected";
  at?: string;
};

export type Stat = {
  label: string;
  value: string | number;
  /** Small delta line under the value: "+3 since last call". */
  hint?: string;
};

export type Shot = {
  src: string;
  caption?: string;
};

export type Moment = { at: string; text: string };

export type Block =
  | { kind: "heading"; title: string; subtitle?: string; span?: Span }
  | { kind: "people"; people: Person[]; span?: Span }
  | { kind: "todos"; title?: string; items: Todo[]; span?: Span }
  | { kind: "decisions"; title?: string; items: Decision[]; span?: Span }
  | { kind: "quote"; text: string; by?: string; span?: Span }
  | { kind: "moodboard"; title?: string; shots: Shot[]; span?: Span }
  /** Diverging meter, -1 (talking past each other) → +1 (converging). 0 is a true neutral. */
  | { kind: "alignment"; title?: string; value: number; note?: string; span?: Span }
  | { kind: "stats"; items: Stat[]; span?: Span }
  | { kind: "agenda"; title?: string; items: { text: string; done?: boolean }[]; span?: Span }
  /** A note surfaced from the second brain mid-call. `source` is shown as provenance. */
  | { kind: "recall"; title?: string; text: string; source?: string; span?: Span }
  | { kind: "timeline"; title?: string; items: Moment[]; span?: Span }
  | { kind: "note"; title?: string; text: string; span?: Span };

export type CanvasDoc = {
  /** Bumped by the producer on every push; the client uses it to ignore out-of-order SSE frames. */
  rev?: number;
  title?: string;
  subtitle?: string;
  /** Rendered as a live pill in the header. */
  status?: "live" | "paused" | "ended";
  /** Transient celebration overlay. Cleared by the producer sending `reaction: null`. */
  reaction?: { kind: "handshake" | "highfive" | "spark"; label?: string } | null;
  blocks: Block[];
};

/** Kinds the renderer knows. Anything else is skipped rather than thrown — see note above. */
export const KNOWN_KINDS = new Set<Block["kind"]>([
  "heading", "people", "todos", "decisions", "quote",
  "moodboard", "alignment", "stats", "agenda", "recall", "timeline", "note",
]);

/** Default column span per kind, so a producer can omit layout entirely and still get a good page. */
export const DEFAULT_SPAN: Record<Block["kind"], Span> = {
  // Spans are chosen so the common orderings tile the 6-column grid without holes: alignment(2) +
  // agenda(4), todos(3) + decisions(3), recall(4) + timeline(2). A gap on a screen share reads as
  // "something failed to load", so defaults that leave one are a bug, not a cosmetic preference.
  heading: 6, people: 6, todos: 3, decisions: 3, quote: 6,
  moodboard: 4, alignment: 2, stats: 6, agenda: 4, recall: 4, timeline: 2, note: 3,
};

/** Cheap stable hash → hue, so a given person keeps their colour across meetings without a registry. */
export function hueOf(seed: string): number {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  return h % 360;
}

export function initialsOf(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (!parts.length) return "?";
  // Vietnamese names are given-name-last, so the LAST token is the one people are called by.
  const last = parts[parts.length - 1][0];
  return (parts.length > 1 ? parts[0][0] + last : last).toUpperCase();
}

/** A full-surface demo so `/canvas` is worth looking at before any pipeline exists. */
export const DEMO_DOC: CanvasDoc = {
  rev: 1,
  title: "QSortby · pilot scoping",
  subtitle: "QDN Digital",
  status: "live",
  blocks: [
    { kind: "people", people: [
      { name: "Phạm Đức Toàn", role: "Product & Growth", key: "toan", speaking: true },
      { name: "Quang", role: "QDN · Founder/CEO", key: "quang" },
      { name: "Linh Trần", role: "QDN · Engineering", key: "linh" },
      { name: "Minami", role: "capturing", key: "minami" },
    ] },
    { kind: "stats", items: [
      { label: "Elapsed", value: "24:10" },
      { label: "Decisions", value: 3, hint: "+2 this segment" },
      { label: "Action items", value: 5, hint: "4 assigned" },
      { label: "Open loops", value: 2, hint: "needs owner" },
    ] },
    { kind: "alignment", value: 0.62, note: "converging on scope" },
    { kind: "agenda", items: [
      { text: "Pilot scope", done: true },
      { text: "Timeline", done: true },
      { text: "Pricing", done: false },
      { text: "Next steps", done: false },
    ] },
    { kind: "todos", title: "Action items", items: [
      { text: "Send the pilot scope doc", owner: "Toàn", due: "Fri" },
      { text: "Confirm staging environment", owner: "Linh", due: "Wed" },
      { text: "Draft pricing options (3 tiers)", owner: "Toàn", due: "Mon" },
      { text: "Share last quarter's sort metrics", owner: "Quang", done: true },
    ] },
    { kind: "decisions", title: "Decided", items: [
      { text: "Pilot runs 6 weeks, not 3 months", status: "agreed", at: "12:04" },
      { text: "Start with one merchant, not the full catalogue", status: "agreed", at: "18:41" },
      { text: "Custom onboarding flow", status: "parked", at: "21:12" },
    ] },
    { kind: "recall", span: 6, title: "From your second brain",
      text: "Last call (18 Jul) you committed to a 6-week pilot window and Quang asked for weekly metrics, not a final report.",
      source: "30-39 Resources/people/QDN/quang.md" },
  ],
};

/** Every block kind on one page — a template gallery for design work, not a realistic meeting.
 *  Reachable at /canvas?demo=full. See the density note below for why this is NOT the default. */
export const DEMO_FULL: CanvasDoc = {
  ...DEMO_DOC,
  rev: 1,
  title: "Canvas · every template",
  subtitle: "design reference — not a realistic meeting",
  blocks: [
    ...DEMO_DOC.blocks,
    { kind: "quote", text: "If it can't show lift inside six weeks, it won't survive the budget cycle.", by: "Quang" },
    { kind: "moodboard", span: 4, title: "Shared screens", shots: [
      { src: "", caption: "Sort dashboard v2" },
      { src: "", caption: "Merchant funnel" },
      { src: "", caption: "Pricing sketch" },
    ] },
    { kind: "timeline", span: 2, title: "Moments", items: [
      { at: "04:12", text: "Budget-cycle constraint raised" },
      { at: "12:04", text: "Agreed 6-week pilot" },
      { at: "18:41", text: "Scope narrowed" },
    ] },
    { kind: "note", span: 6, title: "Note",
      text: "Freeform block — used for anything that isn't a list: a framing, a caveat, a definition the room keeps stumbling over." },
  ],
};

// ── Density: the constraint that actually governs this surface ──────────────────────────────────
// A 1280×720 share is small, and it is read in someone else's video tile while a person talks over
// it. Measured: ~11 blocks forces a 0.65 scale, at which 15px body text renders ~10px — present, but
// not readable at a glance, which is the only kind of reading that happens here.
//
// So the schema is deliberately richer than any single screen should use. Six to eight blocks is the
// working ceiling; past that the producer should DROP the least-live block rather than let the
// renderer shrink everything. Showing less is the feature.
